### ISSUE TITLE
Use a different animated unit for Lithuanians?

### ISSUE THREAD

**Issue by paulirish** [SiegeEngineers/aoe2cm2#112]
This is a super whiny bug report but..

The leitis animation is _very_ dynamic, whereas ~every other unit is in a 'breathing' pose. This makes for mismatch in energy that becomes quite distracting. 

![output](https://user-images.githubusercontent.com/39191/224403552-cd4be501-83d8-4bca-b033-a8fb758d8828.gif)

This especially triggers me while streamers are inbetween tourney games and cm is up on the screen for a long while. The leitis completely steals my attention and it feels out of place. (The samurai might also be too active, but its much lower severity)

----------

I'd be filing this with a proposed replacement, but I was [never successful](https://user-images.githubusercontent.com/39191/224404756-46293f6e-8c71-4099-b602-7c1ce5350e87.gif) in making a good looking one of these. :p  hszemi, i saw you made new ones for the latest expansions.. if you have a script or process, I'd be happy to do the work if it saves time.

**Comment by HSZemi** [comment]
> This is a super whiny bug report but.

No, you are absolutely right.

There might be a second, more idle, idle animation. I'll have to check.

**Comment by HSZemi** [comment]
The Leitis does have one, the Samurai apparently does not :shrug: 
https://github.com/SiegeEngineers/aoe2cm2/releases/tag/2023.4.0

**Comment by paulirish** [comment]
Ahhhh. The new one is perrfect. Thank you
