### ISSUE TITLE
Feature Request: API 

### ISSUE THREAD

**Issue by PatataMaxtex** [SiegeEngineers/aoe2cm2#113]
I would love to get an API-Endpoint that allows me to send a request (for example to https://aoe2cm.net/api/draft/<ID>) that returns the draft with the ID as a JSON.

**Comment by HSZemi** [comment]
Do you mean like this one?
![grafik](https://user-images.githubusercontent.com/3027817/229291481-5551e462-5e5d-4bdc-b769-24d08dd232e3.png)

https://aoe2cm.net/api

**Comment by PatataMaxtex** [comment]
> Do you mean like this one? ![grafik](https://user-images.githubusercontent.com/3027817/229291481-5551e462-5e5d-4bdc-b769-24d08dd232e3.png)
> 
> https://aoe2cm.net/api

Awesome! Didnt found that earlier. Thank you!
