### ISSUE TITLE
Feature request: Add Recent draft notifications to socket.io

### ISSUE THREAD

**Issue by Taloth** [SiegeEngineers/aoe2cm2#116]
Currently the Recent Draft page/api needs to be manually refreshed or polled to see new drafts to spectate. I propose to add a mechanism for realtime notifications of live drafts and finished drafts.

There already is socket.io implemented to provide realtime notification and control of the drafting process to participants and spectators. I propose adding a lobby room to `DraftService.ts`. This room must be notified when a draft goes live or finishes.

**Acceptance Criteria**
- New socket.io query path or param to enter lobby.
- Invalid `draftId` should keep resulting in an error, rather than the lobby, thus preserving current behavior.
- Lobby should be notified when status changes occur in a draft. The notification should include the draftId, presetId, presetName, host & guest names, and ongoing status.
- Recent Drafts UI should:
  - be changed to allow realtime updates of the table. Optionally via on opt-in button.
  - discard oldest draft in list when it's size reaches a specified limit (I suggest a limit in the range of 100-1000).
  - Initialize with most recent 30 draft (current behavior) when reloaded.

**Comment by HSZemi** [comment]
Hm, an automatically refreshing latest drafts page probably would be nice. If anyone wants to implement this, feel free :)

**Comment by HSZemi** [comment]
While the button may get some improvements still, this feature should be complete.
