### ISSUE TITLE
Admin Bans not showing with Simplified UI

### ISSUE THREAD

**Issue by canuckaoe** [SiegeEngineers/aoe2cm2#126]
Admin Bans disappear when using the "Simplified UI" option.

![image](https://github.com/user-attachments/assets/3c308289-e9b0-4dca-a6d4-3bc3527f9f1a)

**Comment by HSZemi** [comment]
That is so silly :upside_down_face: 
Should be a simple fix though.

**Comment by HSZemi** [comment]
Seems like I did this on purpose :shrug: 
Anyway, admin bans are also displayed now.
