### ISSUE TITLE
Mark civs as used during an ongoing match

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/aoe2cm2#16]
Why stop at the end of the draft? Add the option for an organizer to mark civs as used, possibly also reordering the civs and setting whether the match a civ was used in was won or lost.

**Comment by lalitpatel** [comment]
I see that we now have an ability to mark a civilization as used. Was that feature part of this feature request?

**Comment by HSZemi** [comment]
No, this is about further modifying the draft state, whereas what we have now only displays a checkmark locally.

**Comment by lalitpatel** [comment]
Got it. In that case who will have the privilege to mark civilization used globally for all spectators?

**Comment by HSZemi** [comment]
That would probably be a feature for a draft that is created by a tournament admin and sent to the players – a role which is currently not present.

**Comment by simonsan** [comment]
Yeah, as a spectator of a draft I want to see which civs are remaining to be picked. I find the status quo a bit hard to read in that regards.

![2021-05-14 19_04_14-TheViper - Age of Empires II - 2,000 Arabia Invitational 2 _ Ro8, Bo5 vs Nicov _-Screenshot](https://user-images.githubusercontent.com/14062932/118304725-54ea0500-b4e7-11eb-932a-b5ac7b717655.png)

**Comment by HSZemi** [comment]
Everybody can set their own marks. That seems good enough :)
