### ISSUE TITLE
some thoughts

### ISSUE THREAD

**Issue by goto-bus-stop** [SiegeEngineers/aoe2cm2#2]
hopefully not obnoxious, some initial code/structural thoughts from doing #1:

- DraftStore API should probably use promises so it can easily be extended to be persistent in the future (then a process crash will not break all ongoing drafts)
- server and client code could be separate directories ideally
- redux state should be a plain object, not a `Draft` instance (a plain object satisfying the IStoreState interface is fine of course)
- it'd be good to use a localization library already at this stage, it becomes more of a pain to add one the longer you go without

**Comment by HSZemi** [comment]
Absolutely not obnoxious!

Persisting drafts is planned.
Separating server and client code is desirable, but I would still like them to share interfaces etc.
Localization should be the next step, true.
