### ISSUE TITLE
Multiple snipes not working correctly

### ISSUE THREAD

**Issue by athifw** [SiegeEngineers/aoe2cm2#31]
It seems like with multiple snipes, on the second snipe, only civs picked before the sniped civ can be sniped. I have an example preset and draft where this occured:

Draft: https://aoe2cm.net/draft/gFwrw
Preset: https://aoe2cm.net/preset/FyvHP

**Comment by HSZemi** [comment]
I can confirm your observation. Thank you for your report. That is indeed strange. I will look into that.

**Comment by athifw** [comment]
Thanks! This is more obvious when the first picked civ is sniped. After, the only available option is random, and this occurs when "Random" is picked:

![abadi](https://user-images.githubusercontent.com/7432170/84574977-a89c1d80-ad6f-11ea-99f3-abb2362e3e6d.png)

**Comment by HSZemi** [comment]
I have found the issue, basically a missing `,1` in the validation. Expect a fix soon™

**Comment by HSZemi** [comment]
The fix has been deployed, you should be able to snipe properly now. Thanks again for the report :yellow_heart:
