### ISSUE TITLE
Add localization strings for Spanish

### ISSUE THREAD

**Issue by lalitpatel** [SiegeEngineers/aoe2cm2#42]
A lot of AOE II players are Spanish and I think it would be great to have a Spanish (`es_ES`) translation of the site as well.

**Comment by HSZemi** [comment]
- I don't speak Spanish, so I can't help with that
- With four languages, we should probably change the widget that is used to switch languages so a dropdown or something along those lines

**Comment by lalitpatel** [comment]
Yes. I was thinking more of a settings dropdown which has less frequently used settings: language picker + dark theme selector (whenever that is available) 

What do you suggest is best way to source translations? Ask on Discord or may be check with folks on TaToH's stream?
