### ISSUE TITLE
Localise tooltips for the language switcher in the respective language

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/aoe2cm2#49]
Currently, if the language is set to Spanish, all the "Switch language to X" tooltips are in Spanish.

They should of course be in the language that the respective button switches the language to, so 
- the EN button tooltip should always say "Switch language to EN", 
- the Spanish button tooltip should always say "Cambiar el idioma a ES", 
- the German button tooltip should always say "Sprache ändern: DE", and 
- the Chinese button tooltip should always say "将语言设置为 中文".

We could then even hardcode the language in the translation string and would not have to use the short code, so we could say e. g. "Switch language to English".

**Comment by lalitpatel** [comment]
Makes sense.

**Comment by HSZemi** [comment]
Done in 2ab342c1fc5e2b44ae34783ac15e393a16f0d9fd :tada:
