### ISSUE TITLE
Host fonts locally

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/aoe2cm2#50]
For some people with restricted internet access, the site looks like this:
![grafik](https://user-images.githubusercontent.com/3027817/89670886-3e70a680-d8e2-11ea-8b43-11ddc23aca27.png)
If we host the fonts locally, they either get the full page or nothing, but not the page with missing fonts.

**Comment by lalitpatel** [comment]
The Material Icons font has been replaced with the package `mdi-react` in #51 

The heading font 'Crete Round' gracefully falls back to the base font and there is no visible degradation in the user experience. Moreover that font doesn't have Chinese character glyphs so the font is not used whenever the Chinese is selected as the active language.

I would recommend we do not host the heading font (Crete Round).
