### ISSUE TITLE
Programmatic data access

### ISSUE THREAD

**Issue by karx** [SiegeEngineers/aoe2cm2#57]
Is there a way to programmatically fetch a draft's data, an API endpoint or something.

The draft page is dynamically loaded so a HTML parser won't work. Is there something I am missing here?

**Comment by HSZemi** [comment]
Well, there is the socket.io endpoint that the site connects to?

**Comment by HSZemi** [comment]
There is also `https://aoe2cm.net/api/draft/<draft id>` now, which should be simpler to access. It only provides data for finished drafts though.

**Comment by HSZemi** [comment]
https://aoe2cm.net/api/
