### ISSUE TITLE
How long is the lobby stored for?

### ISSUE THREAD

**Issue by B0nisek** [SiegeEngineers/aoe2cm2#64]
Question - how long will the generated link last?

**Comment by HSZemi** [comment]
The answer to your question depends on what you mean with "generated link".

Links to stored presets will last "forever" unless the preset is removed manually.

Links to finished drafts will last forever™ (that means until an accident happens where we lose draft data).

Every hour, running drafts that have _not_ been finished for over six hours get purged, see here:
https://github.com/SiegeEngineers/aoe2cm2/blob/dc56b279e5e2c85fd3670c91cad8efb433508b96/src/models/DraftsStore.ts#L349

**Comment by B0nisek** [comment]
great, thanks for the reply. was asking about finished drafts. thank you
