### ISSUE TITLE
Highlight unpicked civs in the civ selector box for spectators

### ISSUE THREAD

**Issue by lalitpatel** [SiegeEngineers/aoe2cm2#82]
So they are able to see which civs are yet to be picked (by either players).

See: [TheViper talking about it on his stream](https://clips.twitch.tv/BlitheEnergeticPoultryCharlietheUnicorn-gM_zUDIpynFbY55S).

**Comment by HSZemi** [comment]
Scenarios that should be covered by an implementation:
- Parallel turns (show different players' options in their respective colour?)
- Multiple hidden turns one after another (e.g. hidden global picks do influence the available remaining options for the player – just ignore the hidden picks/bans for spectators until they are revealed?)

Think about whether we want to show that to the opponents (why not – but might interfere with picking during parallel turns)

**Comment by HSZemi** [comment]
Added in a67fec2583c5e439d078a3f1787e7cb7b80bc4ac
