### ISSUE TITLE
Descriptions of turns not fitting for advanced mode (e.g. map draft)

### ISSUE THREAD

**Issue by mbergen** [SiegeEngineers/aoe2cm2#89]
When replaying a draft that was created without the regular civilizations, for example a [map draft](https://aoe2cm.net/draft/hkgPC), the descriptions of the turns do not fit.

> Waiting for DauT to ban a civilization
> Waiting for DauT to pick a civilization

when it should be

> Waiting for DauT to ban a map
> Waiting for DauT to pick a map

I see two options:
- Allow for customization of the word used in the description in the preset editor
- Alter those descriptions to be more general

**Comment by mbergen** [comment]
A generic description could be

> Waiting for DauT to decide on a pick
> Waiting for DauT to decide on a ban

**Comment by HSZemi** [comment]
That seems like a good solution!

**Comment by mbergen** [comment]
Found this issue in my open ones, not sure why I didn't close it earlier.
