### ISSUE TITLE
Cannot edit the custom entries for presets after creation

### ISSUE THREAD

**Issue by GrandyB** [SiegeEngineers/aoe2cm2#97]
If you create a new preset using custom picks, e.g. for AoE2 maps, but later realise you got an image wrong or want to re-order the custom options, when you go to 'customise this preset', the "Available Draft Options" isn't set to Custom, and if you do click into it, none of your custom draft options appear.

Would be great if this was possible.

**Comment by HSZemi** [comment]
True. Maybe I can fix this together with the integration of https://github.com/SiegeEngineers/aoe2cm2/pull/95

**Comment by HSZemi** [comment]
@GrandyB If you have a few minutes, can you verify on https://cm.aoe2.se that it behaves as you expect it to?

**Comment by GrandyB** [comment]
Verified.

Created a custom preset, saved preset, went to customise - was on the custom tab and had my existing items in. Saving and re-customising had the extra items I added in between.

Also tried e.g. AoE3 civs with a few unticked, saving and customising again, it had the AoE3 tab open with the correct stuff unticked.

Looks good to me :)

**Comment by HSZemi** [comment]
Aaaand we're live with 3ee697fbd52ba9fc30426c8d186c97853cd91039

Thanks again for the report :yellow_heart:
